"""update_project_and_job

Revision ID: d27cebef5d8a
Revises: 029b9d371938
Create Date: 2026-06-23 17:05:19.388991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27cebef5d8a'
down_revision: Union[str, None] = '029b9d371938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('vocals_url', sa.String(length=512), nullable=True))
    op.add_column('projects', sa.Column('instrumental_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'instrumental_url')
    op.drop_column('projects', 'vocals_url')
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'started_at')
    # ### end Alembic commands ###
